[package]
name = "codesearch-rs"
version = "0.1.0"
authors = ["Vernon Jones <vernonrjones@gmail.com>"]

[dependencies]
byteorder = "0.4.2"
chrono = "0.2"
clap = "1.5.4"
memmap = "0.2.3"
regex = "0.1.44"
regex-syntax = "0.2.2"
log = "0.3.4"
num = "0.1.29"
tempfile = "1.1.3"
hprof = "0.1.3"

[features]
profile = []


[[bin]]
name = "csearch"
path = "src/csearch.rs"
doctest = true

[[bin]]
name = "cindex"
path = "src/cindex.rs"

