[package]
name = "codesearch-rs"
version = "0.1.0"
authors = ["Vernon Jones <vernonrjones@gmail.com>"]
license = "BSD-3-Clause"
description = "Tool for indexing then performing regular expression searches over large bodies of code"
documentation = "https://github.com/vernonrj/codesearch-rs"
homepage = "https://github.com/vernonrj/codesearch-rs"
repository = "https://github.com/vernonrj/codesearch-rs"

[dependencies]
byteorder = "0.4.2"
chrono = "0.2"
clap = "1.5.5"
memmap = "0.2.3"
regex = "0.1.48"
regex-syntax = "0.2.2"
log = "0.3.5"
num = "0.1.30"
tempfile = "1.1.3"
hprof = "0.1.3"
consts = { path = "src/consts" }
customlogger = { path = "src/customlogger" }
csearch = { path = "src/csearch" }
cindex = { path = "src/cindex" }
profiling = { path = "src/profiling" }
varint = { path = "src/varint" }

[features]
profile = []


