[package]
name = "libcsearch"
version = "0.1.0"
authors = ["Vernon Jones <vernonrjones@gmail.com>"]

[dependencies]
byteorder = "0.4"
memmap = "0.2"
num = "0.1"
regex = "0.1"
regex-syntax = "0.4"

consts = { path = "../consts" }
libvarint = { path = "../libvarint" }

